
import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Results from '../components/Result'
import requests from '../utils/requests'

const Home: NextPage = ({results}:any) => {
  //console.log(results)

  return (
    <div >
      <Head>
        <title>Free Streaming Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header></Header>
        <Navbar></Navbar>
        <Results results={results}></Results>




    </div>
  )
}

export default Home;

export async function getServerSideProps(context:any){
  const genre:any = context.query.genre;
  //console.log(context)
  //console.log(genre)
  //console.log('Context query = ',context.query)
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
    )
    const data = await request.json()

  return{
    props:{
      results:data.results,
    }
  }
}
